# Generated by Django 5.1.1 on 2024-10-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
