# Generated by Django 5.1.1 on 2024-10-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('interest_request', 'Interest Request'), ('message', 'Message'), ('general', 'General'), ('interest_accepted', 'Interest Accepted'), ('interest_declined', 'Interest Declined')], default='interest_request', max_length=50),
        ),
    ]
