# Generated by Django 5.1.1 on 2024-11-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
