# Generated by Django 5.1.1 on 2024-11-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_saved_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='saved_image_url',
        ),
    ]
