# Generated by Django 5.1.1 on 2024-11-02 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_notification_read_at_alter_interest_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='interestrequest',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='interestrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='interestrequest',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_interest_requests', to='users.profile'),
        ),
        migrations.AddField(
            model_name='interestrequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interestrequest',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interestrequest',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_interest_requests', to='users.profile'),
        ),
    ]
